# Generated by Django 5.0.6 on 2024-06-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='year_of_studies',
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='marks_or_cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_passing',
            field=models.DateField(),
        ),
    ]
