# Generated by Django 5.0.6 on 2024-06-04 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.CharField(blank=True, max_length=250, null=True)),
                ("education", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "certification",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("experience", models.CharField(blank=True, max_length=250, null=True)),
                ("tech_stack", models.CharField(blank=True, max_length=250, null=True)),
                ("project", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
